import React from "react";
import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="fixed-top header">
        <Link href="/" className="title">
          <h1 className="fw-700">{title}</h1>
        </Link>
      </header>

      <main className="container mx-auto">{children}</main>
    </div>
  );
};

export default Layout;
